### ISSUE TITLE
What is holding back the 2.x release?

### ISSUE THREAD

**Issue by oliversalzburg** [expressjs/cookie-session#122] opened 2019-05-15 13:47 UTC
I was wondering why the 2.x has been standing for so long. What needs to be done?

**Comment by dougwilson** [comment] 2019-05-15 13:50
Duplicate of #118 I believe. Let me know if you have any additional specific questions. Really I haven't migrated most of my production to 2.x yet so I am just not confident in it. If you say it works great in production as it is, I can publish as 2.0.

**Closed by dougwilson** 2019-05-15 13:50 UTC

**Comment by oliversalzburg** [comment] 2019-05-15 14:58
I just bumped our dependency to 2.0.0-beta.3. I'll report back
