### ISSUE TITLE
Renewing the session

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#44] opened 2015-10-09 11:19 UTC
How are we suppose to renew the session?

Using `req.sessionOptions.maxAge =  req.session.maxAge`  within a middle-ware?

**Comment by alvarotrigo** [comment] 2015-10-16 10:57
Isn't this like a very pretty feature of any session component? 
I saw it was marked as a "question" but... isn't there any simple answer for it?

**Comment by dougwilson** [comment] 2015-10-16 13:19
Hi, I'm sorry, but I'm only maintaining this module and did not write it. I don't know enough about it to answer and have not had the time to investigate. I was hoping someone else could answer. I marked it as a question because I assumed it was possible to do what you ask.

If you're saying instead that it's not possible, I can change the label to a feature request instead.

**Comment by alvarotrigo** [comment] 2015-10-16 13:44
> If you're saying instead that it's not possible, I can change the label to a feature request instead.

Nop, just asking as I believe documentation doesn't provide the necessary information.

**Comment by dougwilson** [comment] 2015-10-16 13:47
> Nop, just asking as I believe documentation doesn't provide the necessary information.

Gotcha, that's what I thought and why I labeled this as a question :) The answer from me is "I don't know", which is why I just labeled it and didn't provide an answer. I'll try to take a look into it sometime in the next few weeks if no one else stops by with an answer :)

**Comment by alvarotrigo** [comment] 2015-10-16 13:51
Sometimes I wonder how is it possible these modules get downloaded [70K times a month](https://www.npmjs.com/package/cookie-session) and their documentation and support is so limited. 

I might be used to other platforms, but Node never stops surprising me.

**Comment by alvarotrigo** [comment] 2015-10-21 12:14
`req.sessionOptions` seems to be always empty:

```javascript
app.use(function(req,res,next ){
    console.log(req.session.user);  //user data
    console.log(req.sessionOptions); //empty array
});
```

**Comment by dougwilson** [comment] 2015-10-21 12:58
Hi! Yes, the documentation says:

> These options are a shallow clone of what was provided at middleware construction

Did you provide any options at your middleware construction time? It just contains whatever you gave to the module's constructor. Can you show a full app that reproduces?

**Comment by alvarotrigo** [comment] 2015-10-21 13:33
> Did you provide any options at your middleware construction time?

I did as far as I know:

```javascript
app.use(cookieSession({
  maxAge: 3 * 1000, //20*60*1000, //20 mins
  httpOnly: true,
  secure: true,
  secureProxy: true,
  keys: ['key1', 'key2']
}));

app.use(function(req,res,next ){
    console.log(req.session.user);  //user data
    console.log(req.sessionOptions); //empty array

    req.sessionOptions.maxAge: 4000;
    console.log(req.sessionOptions); //  (maxAge: 4000)

   return next();
});
```

I managed to solve the problem with the renew of the session thanks to [this answer in stackoverflow](http://stackoverflow.com/questions/33169002/renewing-cookie-session-for-express-js/33259017#33259017).

Although I'm not quite sure yet why updating a `fake` session has anything to do with the renew of `session.user` maxAge.

**Comment by dougwilson** [comment] 2015-10-21 13:45
Hmm. Perhaps the issue is with your `console.log(req.sessionOptions)` statement? What happens if you replace both `console.log(req.sessionOptions)`s with `console.log(req.sessionOptions.maxAge)` in your program above? And what if you replace both with `console.log(JSON.stringify(req.sessionOptions))`?

**Comment by alvarotrigo** [comment] 2015-10-21 14:39
Interestingly `console.log(req.sessionOptions.maxAge)` shows the original value.
Not `console.log(req.sessionOptions)`  or `console.log(JSON.stringify(req.sessionOptions))`

**Comment by dougwilson** [comment] 2015-10-21 14:43
Gotcha, that's what I was expecting from how Node.js works. It sounds like everything is working just fine, then to me. Do you have some kind of use-case in your application to do a `console.log(req.sessionOptions)`?

**Comment by alvarotrigo** [comment] 2015-10-21 15:10
> Gotcha, that's what I was expecting from how Node.js works.

Why is it?

**Comment by dougwilson** [comment] 2015-10-26 01:07
> Why is it? 

```
$ node -e 'obj={a:1};console.log(Object.create(obj));console.log(obj.a)'
{}
1
```

**Comment by dougwilson** [comment] 2015-10-26 01:16
The exact same command in Firefox is the following:
```
> obj={a:1};console.log(Object.create(obj));console.log(obj.a)
Object { a=1 }
1
```

**Comment by codeaholics** [comment] 2016-01-05 10:29
The referenced PR (#49) worked for me - once I added the missing call to `next()` :-)

**Comment by Bluejay47** [comment] 2016-06-12 02:25
I brought up the possibility of adding some method to wrap and standardize the process mentioned in https://github.com/expressjs/cookie-session/pull/49 if there is a consensus that doing so make sense.

**Comment by dougwilson** [comment] 2016-11-11 04:52
I think this question was answered, and there is a PR even that would add an example to the README.

**Closed by dougwilson** 2016-11-11 04:52 UTC
Labels: question
