### ISSUE TITLE
Req Session Empty

### ISSUE THREAD

**Issue by nycoh** [expressjs/cookie-session#105] opened 2018-08-11 21:20 UTC
0
down vote
favorite
Im trying to create a cookie-session to authenticate users in my routes, when the use logs in i set the session:

```
router.post('/login', (req, res, next) => {
    model.User.findOne({
        email: req.body.email,
        password: hash(req.body.password)
    }).lean().exec().then(
        user => {
            if (!user) {
                return res.status(401).send({message: 'Invalid email and/or password'});
            }
            req.session.user = user;
            req.session.authorized = true;
            console.log(req.session);
            return res.send({token: createJWT(user)});
        }
    ).catch(next);
});
```
that console log shows the session correctly but then when i try to authenticate my routes

```
 const {Router} = require('express');
const winston = require('winston');
 
 module.exports = router => {
     winston.info('Loading public-api...');
     router.use('/', require('cors')(), require('./public-api')(Router()));
 
     router.use('/api', require('cors')(), require('./api')(Router().use(global.app.security.authorize())));
 
     router.use('/auth', require('cors')(), require('./auth')(Router()));
};
```

then the authorize service

```
module.exports = () =>
    (req, res, next) => {
    console.log(req.session);
        if (req.session.authorized) {
            req.user = req.session.user;
            return next();
        }
    };
```
here req.session is empty.

**Comment by dougwilson** [comment] 2018-08-11 21:24
I'm not sure. I can investigate the issue, though. Please provide all the following so I can reproduce the issue:

1. Version of Node.js, this module, and all other involved modules
2. Complete source code I can copy and paste and run without modification.
3. Complete instructions on how to reproduce the issue after running the above code.

Thanks!

**Comment by nycoh** [comment] 2018-08-11 22:13
That would be a bit complicated but i think i found out where can the problem be, my server is hosted in localhost:6000 but the client makeing the requests is in localhost:3000. im i lacking something to make it work?

**Comment by dougwilson** [comment] 2018-08-11 22:16
So it doesn't need to be your actual code, just complete code I can run to reproduce the issue. The easiest way to do that is how you already determined it was a bug in this module: take your current code and start removing things. Validate issues still exists and repeat eventually you'll have some bare code left that reproduces the issue and doesn't have anything secret in it you can share.

If you have another proposal for how I can debug the issue to help with a fix that does not involve sharing a reproduction with me, please let me know and I'm happy to take that approach  +1:

**Comment by d-jiang** [comment] 2018-08-23 09:38
from the instruction, cookie-session will auto set a cookie in browser,
but it seems like doesn't work in my project.

node --version           v10.8.0
"express":                   "~4.16.0",
"cookie-session":      "^2.0.0-beta.3",

express.Router() has been used in my project.

The code below is configuration of cookie-session
`
app.use(cookieSession({
  name: 'session',
  keys: confs.sessionKeys(),
  maxAge: 7 * 24 * 60 * 60 * 1000 // 24 hours
`

Thanks

**Comment by dougwilson** [comment] 2018-08-23 12:33
Closing since my requests for information are just ignored.

**Closed by dougwilson** 2018-08-23 12:33 UTC
Labels: awaiting more info
