### ISSUE TITLE
Cookie session no longer stored on chrome if request originates from cross origin http server

### ISSUE THREAD

**Issue by AjinkyaBijwe** [expressjs/cookie-session#161] opened 2022-03-04 12:21 UTC
**Scenario 1:** 
origin: localhost:4200
destination: 192.168.1.161:8081
cookie settings : {
  name: "session",
  keys: ["cat"],
  maxAge: 24 * 60 * 60 * 1000
}

**Scenario 2:**
origin: localhost:4200
destination: 192.168.1.161:8081
cookie settings : {
  name: "session",
  keys: ["cat"],
  maxAge: 24 * 60 * 60 * 1000,
 sameSite: "none"
}

<img width="603" alt="image" src="https://user-images.githubusercontent.com/8812357/156762510-213a3043-37f1-42c5-9f2f-cbbe0956f38b.png">

**Comment by dougwilson** [comment] 2022-03-04 13:44
Hello, and sorry you are having an issue. The Chrome warning seems to indicate that you need to add `secure: true` to your options to this module.

**Comment by AjinkyaBijwe** [comment] 2022-03-05 05:47
even when I add secure : true it is not storing cookie for HTTPS origin

**Comment by dougwilson** [comment] 2022-03-05 05:52
Hi, very strange. I'm not sure what is going on, unfortunately. Would you be willing to either put togeher a full app and instructions that I can run to reproduce the issue or a pull request with the neede changes?

**Comment by tungdmctv** [comment] 2022-03-18 03:02
I've got the same issue, event I try with cookie secure true

```
app.use(
  session({
    secret: "xxxxxxx",
    resave: false,
    saveUninitialized: true,
    cookie: { secure: true, maxAge: 20 * 60 * 1000 },
  })
);
```

and I also set CORS :
```
app.use(
  cors({
    origin: '*'
    methods: ["POST", "PUT", "GET", "OPTIONS", "HEAD"],
    credentials: true,
  })
);
```

when get or set session I'm using

req.session[KEY]

while I try to make request from browser using Axios and also XMLHttpRequest, these didn't work. The Session not store on server.

```
axios.get( URL , {  credentials: true  })

var xmlHttp = new XMLHttpRequest()
        xmlHttp.open('GET', URL, false)
        xmlHttp.send()

```
and I also tried on server with HTTPS.

please give suggestion.

**Comment by dougwilson** [comment] 2022-03-23 17:37
Closing due to no app provided to repliacte. You're always welcome to either provide the requested information or a pull request witha fix.

**Closed by dougwilson** 2022-03-23 17:37 UTC
Labels: awaiting more info
