### ISSUE TITLE
Cannot set property length of #<Session> which has only a getter

### ISSUE THREAD

**Issue by timburcham** [expressjs/cookie-session#39] opened 2015-09-25 16:47 UTC
Using Node 4.1.1, and cookie-session 1.2.0, I get this error upon making any request.  Reverting to 1.1.0 eliminates the error.  I can't tell if this is an issue with the lib, or an issue with my implementation?  Not doing anything very fancy with it.

```
TypeError: Cannot set property length of #<Session> which has only a getter
   at new Session (/Library/WebServer/Documents/__/node_modules/cookie-session/index.js:145:17)
```

``` js
function Session(ctx, obj) {
  this._ctx = ctx

  Object.defineProperty(this, 'isNew', {
    value: !obj
  })

  if (obj) {
    for (var key in obj) {
      this[key] = obj[key]
    }
  }
}
```

**Comment by dougwilson** [comment] 2015-09-25 16:49
I'm not able to reproduce with the information provided. Would be be possible to provide a minimal app that uses this module that reproduces the issue?

**Comment by dougwilson** [comment] 2015-09-25 16:50
To me, it seems like perhaps you are trying to store a key named "length" in your session object?

**Comment by timburcham** [comment] 2015-09-25 17:02
Let me look at a minimal app.  And thank you for the tip on looking at key named 'length' -- the language on the error was sending me down a different path.

**Comment by timburcham** [comment] 2015-09-25 19:09
Still assembling a minimal app, but this seems to be Passport interacting with cookie-session, passing in the 'length' property.

**Comment by timburcham** [comment] 2015-09-25 21:26
So, after digging further and eliminating dependencies, I was able to narrow in on this line of code in the implementation:

req.session = req.session || {};

This takes the Session object, and sends it back through the setter for the Session object.  The 'length' property on the base Session object causes the error mentioned.

I can fix this by using a different defaulting syntax, @dougwilson your call if this type of use case warrants checks inside of the setter.

**Comment by dougwilson** [comment] 2015-09-25 21:43
Ah, I see. I assume the `req.session = req.session || {};` is in different code, correct? We may have this case already fixed on the `master` branch here, if you want to confirm. `npm i expressjs/cookie-session` to try it out.

**Comment by timburcham** [comment] 2015-09-25 21:45
Right, that bit is in my own code.

**Comment by dougwilson** [comment] 2015-10-12 04:56
Hey @timburcham , did you ever confirm if this behavior was fixed in `master` or not?

**Comment by dougwilson** [comment] 2016-11-11 04:55
Closing from no response. I assume it is fixed in `master`, then :)

**Closed by dougwilson** 2016-11-11 04:55 UTC

**Comment by jeffbmartinez** [comment] 2020-05-05 04:57
@dougwilson 

FWIW, I just ran into the same problem.

The code:
`req.session = req.session || {};`

Produces the same error:
`TypeError: Cannot set property length of #<Session> which has only a getter`

I got around it by changing to:
```
if (!req.session) {
  req.session = {};
}
```

## Relevant Version Info

`package-lock.json`:
```
"cookie-session": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/cookie-session/-/cookie-session-1.4.0.tgz",
      "integrity": "sha512-0hhwD+BUIwMXQraiZP/J7VP2YFzqo6g4WqZlWHtEHQ22t0MeZZrNBSCxC1zcaLAs8ApT3BzAKizx9gW/AP9vNA==",
      "requires": {
        "cookies": "0.8.0",
        "debug": "2.6.9",
        "on-headers": "~1.0.2"
      }
    },
```

```
$ node --version
v12.16.2
```

**Comment by dougwilson** [comment] 2020-05-05 05:02
Hi @jeffbmartinez that is not the current `master` version, which is ideally where we'd want to fix the issue in to fix forward. Can you test the 2.0.0 beta?

**Comment by jeffbmartinez** [comment] 2020-05-05 05:28
@dougwilson Happy to help debug a little closer tomorrow, but for tonight I'm off to get some sleep. I did investigate a little further since my last message. It looks like the problem (indeed, in `1.4.0`) has to do with the for loop inside of `Session`:

```
function Session(ctx, obj) {
  this._ctx = ctx

  Object.defineProperty(this, 'isNew', {
    value: !obj
  })

  if (obj) {
    for (var key in obj) {
      console.log('trying', key);
      this[key] = obj[key] // PROBLEM <-- when key === 'length' there is no matching Session.prototype.__defineSetter__(...)
      console.log('succeeded', key);
    }
  }
}
```

From a quick glance at `master`, it's probably fixed, given you're now using `.defineProperty` instead of the `__defineG/Setter__` style and `'length'` is gone too.

**Comment by dougwilson** [comment] 2020-05-05 05:29
Ah. Yea, setting the length of the session doesn't make sense, which is why there is no setter. For example, if the session has 5 keys, but you update the value to 8, what are those three new keys even supposed to be? That's why there is no setter, as there is no meaningful action to take when doing `req.session.length = 8` for example.

**Comment by jeffbmartinez** [comment] 2020-05-05 05:36
@dougwilson Ended up testing it real quick. `req.session = req.session || {};` works just fine with `2.0.0-rc.1`.

And yeah, makes sense what you're saying about setting the length :)

Thanks for the hard work btw!

**Comment by brewmanandi** [comment] 2021-06-02 14:50
one year later - still an issue
