### ISSUE TITLE
HTTPS to HTTP issue - Losing the cookie?

### ISSUE THREAD

**Issue by canaanites** [expressjs/cookie-session#89] opened 2017-10-19 00:29 UTC
Hello,

I have an issue when I login to my website via HTTPS and then try to login via HTTP.
My req.session returns empty object via HTTP, but it works fine with HTTPS.

However, when I _clear site data_, I can successfully login via HTTP. 
The problem occur when I login via **HTTPS** --> logout --> login via **HTTP** - I can't login again unless I clear site data

**NOTE:**  I've tried to check the cookies in Dev Tool; however, I don't get the cookie when I try to login via **HTTP**. Again, it works fine via HTTPS.

This is what I use in my code:

	app.use(bodyParser.urlencoded({ extended: false }));

	app.use(bodyParser.json());

	app.use(cookieSession({
		name: 'session',
		keys: sessionKeys,

		// Cookie Options
		maxAge: 24 * 60 * 60 * 1000 // 24 hours
	}));

--------
	function checkAuth(req, res, next) {
		if (!req.session.user_id) {
			res.redirect('/login/');
			//res.send('You are not authorized to view this page');
		} else {
			next();
		}
	}

-------
      app.get('/dashboard', checkAuth, function(req, res){
		res.sendFile(__dirname + '/dashboard.html');
		app.use(express.static('.'));
	});

**Comment by dougwilson** [comment] 2017-10-19 00:54
Yes, this is the default behavior (https://github.com/expressjs/cookie-session#cookie-options). The `secure` option defaults to `true` when over HTTPS and `false` when over HTTP unless you specifically set it. If you want it to work on both, you'll want to specifically add `secure: false` to the options :)

**Comment by canaanites** [comment] 2017-10-19 02:09
@dougwilson Thank you so much for the reply!  I have already tried this, but it didn't help fix the problem :(

When I add **secure: false**, I can't login even after _clearing the site data_
	app.use(cookieSession({
		secure: false,
		name: 'session',
		keys: sessionKeys,

		// Cookie Options
		maxAge: 24 * 60 * 60 * 1000 // 24 hours
	}));

I also noticed I get error 302 for the /dashboard/

**Comment by dougwilson** [comment] 2017-10-19 02:25
Hi @canaanites . That is weird. I pieced together the code you gave and ran it before that suggestion. Perhaps there is something different between our code and you can help me reproduce the issue. Can you provide the following?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete source code where I don't have to fill anything in so we have the exact same code on both our sides.
4. Instructions for how to reproduce the issue.

Thanks!

**Comment by canaanites** [comment] 2017-10-19 03:41
Hi @dougwilson , sorry for the delayed response. Hope this help!

1. Version of Node.js you are using:  Node.js v8.5.0 / NPM v5.3.0
2. Version of this module you are using:  express@4.15.3
3. Source code (I can't share the entire source code due legal polices): https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e
4. Instructions for how to reproduce the issue:  I just do **node server.js** and the app should run fine.
**NOTE** I'm using Redhat Linux and I redirect port 80 --> 3001 & port 443 --> 3000 via iptables

**Comment by canaanites** [comment] 2017-10-20 16:16
Hi @dougwilson, I've updated my answer.

**Comment by dougwilson** [comment] 2017-10-20 16:41
Thanks, @canaanites . I haven't gotten it up and running because it seems there are a lot of instructions left out, and I'm working on trying to figure out what needs to be done. I had a lot of missing module issues which I fixed by installing the latest versions (is that right? do you know which modules I should be installing to run this and which versions?), but I get an error trying to read the key files since I don't have them, and not sure what should be there and then also the `/login/` errors even if I comment that part out because I don't have the HTML for that page.

**Comment by dougwilson** [comment] 2017-10-20 16:43
There was also nothing in your code that was listening on port 3000 or 3001, only 3002, so I wasn't sure what should have been on 3000 / 3001, and maybe I guessed wrong.

**Comment by dougwilson** [comment] 2017-10-20 16:45
I changed `domain.com:3002` to `localhost:3002` as well, which wasn't part of the instructions you provided, so not sure if that was what I was supposed to do.

**Comment by canaanites** [comment] 2017-10-20 16:55
Hey @dougwilson , I think you're getting missing modules because my modules, in the code, are pointing to the local/dev node_modules folder (not global). Example: var express = require(**'./node_modules/express'**). This might have to be require(**'express'**)

for 3000 & 30001, they are at line 101 and 107
https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e#file-server-js-L101

	//HTTP Server
	var port = process.env.PORT || 3001 ;
	server.listen(port, function(){
		console.log('server started on port: 3001');
	});

	//HTTPS Server	
	var portS = process.env.PORT || 3000 ;
	serverS.listen(portS, function(){
		console.log('server started on port: 3000');
	});


For port 3002, I use that just to get the keys and use it for the session and crypto. It could be either localhost or remote-host

**Comment by dougwilson** [comment] 2017-10-20 17:04
Gotcha. Can you provide a list of all the things I need to change to get it to work? I only have a little time here and there, and I spent my entire break today trying to get it to work without success. I can take a look another day, but the less I have to figure out to get it to run, the faster I can get to debugging your actual issue :)

**Comment by dougwilson** [comment] 2017-10-20 17:15
And of course, forgot to mention, I'm always open to taking a PR with the fix as well 👍

**Comment by canaanites** [comment] 2017-10-20 17:22
@dougwilson  for sure:

1. change [**this** ](https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e#file-server-js-L26)to '127.0.0.1' 
2. change  [**this**](https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e#file-server-js-L26) to 'localhost:3002'
3. create key and crt and add them to [**this** ](https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e#file-server-js-L12) option 
4. Make sure you have socket.io. Change [**this**](https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e#file-server-js-L12) to point to the correct node_modules folder. 
5. You might have to change the rest of the modules to point to the correct node_modules folder
6. Change [**checkUserFromTheDB**](https://gist.github.com/canaanites/f1455130a48ed9cea0332e34aa992b3e#file-server-js-L150) to **TRUE**, assuming the credential are correct to login

**Comment by dougwilson** [comment] 2017-10-20 17:25
I'm not sure if you saw the other issue I mentioned, whixh was after I hacked it up to work, going to /login/ errored because I don't have the HTML for the page. What should it be?

**Comment by dougwilson** [comment] 2017-10-20 23:05
Ideally specific instructions for how to get past the following errors:
```
$ node server.js
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\opt\certs\key'
```

For now I commented out the SSL stuff.

```
$ node server.js
Unable to parse response as JSON SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (server.js:51:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (server.js:51:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
server.js:76
                throw err;
                ^

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (server.js:51:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Then I commented out a whole lot of stuff to get past that and then:
```
Error: ENOENT: no such file or directory, stat 'login.html'
    at Error (native)
```

And that last one I'm not able to comment out past since without it I don't get a page to load at /login/

**Comment by dougwilson** [comment] 2018-02-27 02:58
Closing since I never heard back.

**Closed by dougwilson** 2018-02-27 02:58 UTC
Labels: awaiting more info
