### ISSUE TITLE
Cookie session wouldn't keep data unless using Incognito Window in Chrome

### ISSUE THREAD

**Issue by alvarotrigo** [expressjs/cookie-session#79] opened 2017-05-10 10:01 UTC
I had this problem a couple of times before. It seems to take place only from time to time.
The session wouldn't keep the data on a `redirect` unless I did the same action on an Incognito Window using Chrome. (Or incognito window in any other browser).

The exact same code was working properly in Incognito as well as in production. 

Only after I went to Chrome Developer Tools and click on `Application / Clear Storage / Select all boxes / Clear selected` , I was able to get the cookie session to be shared around my app.

Notice, this was not working even after removing manually the `Local Storage`,`Session Storage` and `Cookies` from the left panel.

![cookie session](https://cloud.githubusercontent.com/assets/1706326/25893447/c2249398-356f-11e7-902b-2baf3ecec836.JPG)

```javascript
     req.session.user = {
          test: 'test'
     };

     //req. session.user would be `undefined` after this unless in incognito
     res.redirect('/');
````

Am I doing anything wrong? What am I missing?
Why the same code works ok in other computer or in incognito?

**Comment by dougwilson** [comment] 2017-05-11 02:38
That is very weird. Is it possible to share the following so I can poke at it?

1. Version of Node.js and this module
2. Code to run that reproduces this
3. Some instructions on what to load / browse in the browser to reproduce

I'm only asking because I have no ideas off-hand, so wanted to poke at it to see if I could come up with something.

**Comment by dougwilson** [comment] 2017-07-11 07:42
Closing since I never heard back.

**Closed by dougwilson** 2017-07-11 07:42 UTC
Labels: awaiting more info

**Comment by RobQuistNL** [comment] 2018-10-04 13:52
I'm actually having a similar issue, but with a PHPSESSID from PHP, not related to  expressJS, so I guess its something in chrome... Just dont know what :(

It doesn't save the PHPSESSID in a regular browser, but it does in an ingocnito window. Very odd.
